import React from 'react';
import type { IncidentFilters as FilterValues } from './types';
import { formatLabel } from './utils';

export const IncidentFilters: React.FC<{ value: FilterValues; onChange: (value: FilterValues) => void }> = ({ value, onChange }) => {
  const set = (key: keyof FilterValues, next: string) => onChange({ ...value, [key]: next || undefined });
  const select = (label: string, key: keyof FilterValues, values: string[]) => <label className="text-xs font-semibold text-slate-500">{label}<select value={(value[key] as string) ?? ''} onChange={(event) => set(key, event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800"><option value="">All</option>{values.map((item) => <option key={item} value={item}>{formatLabel(item)}</option>)}</select></label>;
  return <div className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 md:grid-cols-4">
    <label className="text-xs font-semibold text-slate-500 md:col-span-2">Search<input value={value.search ?? ''} onChange={(event) => set('search', event.target.value)} placeholder="Title, description, or address" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    {select('Disaster Type', 'disaster_type', ['flood', 'fire', 'earthquake', 'cyclone', 'landslide', 'industrial_accident', 'chemical_leak', 'road_accident', 'medical_emergency', 'other'])}{select('Status', 'current_status', ['reported', 'under_review', 'verified', 'in_progress', 'resolved', 'closed'])}
    {select('Severity', 'severity', ['low', 'moderate', 'high', 'critical'])}{select('Verification', 'verification_status', ['unverified', 'pending', 'verified', 'rejected'])}
    {select('Reporter Type', 'reporter_type', ['citizen', 'first_responder', 'government_agency', 'ngo', 'sensor', 'other'])}
    <label className="text-xs font-semibold text-slate-500">From<input type="date" value={value.created_from?.slice(0, 10) ?? ''} onChange={(event) => onChange({ ...value, created_from: event.target.value ? `${event.target.value}T00:00:00Z` : undefined })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    <label className="text-xs font-semibold text-slate-500">To<input type="date" value={value.created_to?.slice(0, 10) ?? ''} onChange={(event) => onChange({ ...value, created_to: event.target.value ? `${event.target.value}T23:59:59Z` : undefined })} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    <label className="text-xs font-semibold text-slate-500">Location Lat<input type="number" step="any" value={value.location_latitude ?? ''} onChange={(event) => onChange({ ...value, location_latitude: event.target.value ? Number(event.target.value) : undefined })} placeholder="-90 to 90" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    <label className="text-xs font-semibold text-slate-500">Location Lng<input type="number" step="any" value={value.location_longitude ?? ''} onChange={(event) => onChange({ ...value, location_longitude: event.target.value ? Number(event.target.value) : undefined })} placeholder="-180 to 180" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    <label className="text-xs font-semibold text-slate-500">Radius (km)<input type="number" step="any" min="0" value={value.location_radius_km ?? ''} onChange={(event) => onChange({ ...value, location_radius_km: event.target.value ? Number(event.target.value) : undefined })} placeholder="GIS filtering later" className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-800" /></label>
    <label className="flex items-end gap-2 text-sm font-medium"><input type="checkbox" checked={value.include_archived ?? false} onChange={(event) => onChange({ ...value, include_archived: event.target.checked })} /> Include archived</label>
    <button type="button" onClick={() => onChange({})} className="self-end rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Clear filters</button>
  </div>;
};
